rough draft - sg run docsite removed
sourcegraph/docs pull request #218
Opened 2024-03-28 22:47 UTC by DaedalusG

This is a rough draft start at removing references to old the `sg run docsite` tooling for running docs locally

Reviewing where it was referenced its clear theres other types of references that need updated too, so I'll start a branch here for it.

2024-04-01 17:55 UTC, MaedahBatool requested changes
Leaving some comments and feedback. The same feedback applies on our versioned 5.2 docs as well. :)

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +git clone https://github.com/sourcegraph/docs.git sourcegraph-docs
```suggestion
git clone https://github.com/sourcegraph/docs.git 
```

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +cd sourcegraph-docs
```suggestion
cd docs
```

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +<!-- Needs Review -->
We need to update this. All this section of updating docs.

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +<!-- Needs Review -->
We can remove this section since there is no frontmatter.

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +<!-- Needs Review -->
We also need to edit this part as it mentions docs.sourcegrpah.com

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +<!-- Needs Review -->
Edit this part as well. The local server lies on port 3000.

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/documentation_implementation.mdx
> +<!-- Needs Review -->
I think we can remove it.

2024-04-01 17:55 UTC, MaedahBatool commented on docs/dev/how-to/monitoring_local_dev.mdx
> +<!-- Needs Review -->
This part is still valid. We are still using autogenerated docs from Docsite.

2024-04-01 17:55 UTC, MaedahBatool commented on docs/versioned/5.2/dev/how-to/documentation_implementation.mdx
> +git clone https://github.com/sourcegraph/docs.git sourcegraph-docs
```suggestion
git clone https://github.com/sourcegraph/docs.git 
```

2024-04-01 17:55 UTC, MaedahBatool commented on docs/versioned/5.2/dev/how-to/documentation_implementation.mdx
> +cd sourcegraph-docs
```suggestion
cd docs
```

2024-04-29 09:09 UTC, jhchabran commented
@DaedalusG given we removed the dev docs from this repo, I think we can close this.

2024-04-29 09:09 UTC, closed without merging