add Cody role based access control docs
sourcegraph/docs pull request #31
Opened 2024-01-11 00:20 UTC by slimsag

Corresponding docs for https://github.com/sourcegraph/sourcegraph/pull/58831

2024-01-11 19:11 UTC, MaedahBatool requested changes
Left some comments basically around structure. Rest looks good. Thanks for contributing. :)

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +<details>
```suggestion

```
These HTML tags will not work. We will soon get a `toggle` component that will make it easier. Till then we can use an H3. :)

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +<summary>Sourcegraph 5.3+</summary>
```suggestion
### Sourcegraph 5.3+
```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +**Note:** Ensure `cody.restrictUsersFeatureFlag` is NOT in your site configuration. If it is, remove it or else the old feature-flag approach from Sourcegraph 5.2 and earlier will be used.
```suggestion
<Callout type="note"> Ensure `cody.restrictUsersFeatureFlag` is **not** in your site configuration. If it is, remove it or else the old feature-flag approach from Sourcegraph 5.2 and earlier will be used.</Callout>
```

We have a component called `Callout` for `note`, `info`, `tip`, and `warning` types.

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +* Control whether users _by default_ have access to Cody (expand `User [System]` and toggle **Cody** > **Access** as desired)
```suggestion
- Control whether users _by default_ have access to Cody (expand `User [System]` and toggle **Cody** > **Access** as desired)
```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +* Control whether groups of users have access to Cody (`+Create role` and enable the **Cody** > **Access** toggle as desired)
```suggestion
- Control whether groups of users have access to Cody (`+Create role` and enable the **Cody** > **Access** toggle as desired)
```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +</details>
```suggestion

```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +<details>
```suggestion

```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +<summary>Sourcegraph 5.2 and earlier</summary>
```suggestion
### Sourcegraph 5.2 and earlier
```

2024-01-11 19:11 UTC, MaedahBatool commented on docs/cody/clients/enable-cody-enterprise.mdx
> +</summary>
```suggestion

```

2024-01-12 01:28 UTC, slimsag commented
@MaedahBatool done!

2024-01-12 20:00 UTC, MaedahBatool approved these changes

2024-01-12 20:00 UTC, merged