search-jobs: document new result format
sourcegraph/docs pull request #40
Opened 2024-01-17 12:55 UTC by stefanhengl

Relates to https://github.com/sourcegraph/sourcegraph/pull/59619

We have moved from CSV to JSON as the new export format.

Note: I also fixed some typos and tweaked the copy a bit. Several customers have asked about the ENVs for the blobstore so I made it more explicit that the blobstore doesn't require setting any ENVs.

2024-01-17 18:29 UTC, MaedahBatool requested changes
Leaving some feedback. :)

2024-01-17 18:29 UTC, MaedahBatool commented on docs/code_search/how-to/search-jobs.mdx
> +<Callout type="note" title="Enterprise only"> Search Jobs is available only on Enterprise accounts.</Callout>
```suggestion

```
Let's adjust both info in the callout above.

2024-01-17 18:29 UTC, MaedahBatool commented on docs/code_search/how-to/search-jobs.mdx
>  <Callout type="note" title="Experimental"> Search Jobs feature is in the Experimental stage.</Callout>
```suggestion
<Callout type="note" title="Experimental"> Search Jobs feature is in the Experimental stage and available for only Enterprise accounts.</Callout>
```

2024-01-17 18:29 UTC, MaedahBatool commented on docs/code_search/how-to/search-jobs.mdx
> +Each line of the results file is a JSON object containing matches. The JSON objects have the same format as the (event-type) matches served by the [Stream API](/stream_api/#Event-types).
```suggestion
Each line of the results file is a JSON object containing matches. The JSON objects have the same format as the (event-type) matches served by the [Stream API](/api/stream_api#event-types).
```
wrong link path.

2024-01-17 18:29 UTC, MaedahBatool commented on docs/code_search/how-to/search-jobs.mdx
> +By default, Search Jobs stores results using our bundled `blobstore` service. If the `blobstore` service is deployed, and you want to use it to store results from Search Jobs you can skip ahead to [s
```suggestion
By default, Search Jobs stores results using our bundled `blobstore` service. If the `blobstore` service is deployed, and you want to use it to store results from Search Jobs you can skip ahead to [site administration](/code_search/how-to/search-jobs#site-administration) To target a third-party managed object storage service, you must set a handful of environment variables for configuration and authentication to the target service.
```

2024-01-22 14:14 UTC, stefanhengl commented
Thanks for the feedback @MaedahBatool. I accepted all your suggestions. PTAL

2024-01-22 19:04 UTC, MaedahBatool approved these changes

2024-01-22 19:04 UTC, MaedahBatool commented
Approved let's merge it.

2024-01-23 09:19 UTC, merged