updates to cloud trials
sourcegraph/docs pull request #46
Opened 2024-01-19 18:55 UTC by amenne

This PR does the following:

1. Updates to cloud trial language, removing previous restrictions and reference to 30 day trials (account team will align on timeline)
2. Updates references to features compatible with cloud
3. Removes section on Cody and instead directs user to Cody pages

2024-01-19 19:03 UTC, MaedahBatool requested changes
Thanks for contributing. Left some small feedback.

2024-01-19 19:03 UTC, MaedahBatool commented on docs/cloud/index.mdx
> +- [Cody](../cody/index.mdx)
```suggestion
- [Cody](/cody)
```
Link path fix

2024-01-19 19:03 UTC, MaedahBatool commented on docs/cloud/index.mdx
> +- [Code Insights](../code_insights/index.mdx)
```suggestion
- [Code Insights](/code_insights/)
```
Link path fix.

2024-01-20 00:02 UTC, amenne commented
Thanks @MaedahBatool committed suggestions on the links. Good to merge?

2024-01-22 19:03 UTC, MaedahBatool commented
@amenne yes, we are good to go. I am merging it. :)

2024-01-22 19:03 UTC, MaedahBatool approved these changes

2024-01-22 19:04 UTC, merged