Update ssh repo clone docs
sourcegraph/docs pull request #669
Opened 2024-09-24 22:58 UTC by michaellzc

## Pull Request approval

Although pull request approval is not enforced for this repository in order to reduce friction, merging without a review will generate a ticket for the docs team to review your changes. So if possible, have your pull request approved before merging.

2024-09-24 22:59 UTC, michaellzc commented
* **#669** <a href="https://app.graphite.dev/github/pr/sourcegraph/docs/669?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @michaellzc and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-25 15:24 UTC, loujar reviewed
I think we should also update the [_Configuration_ sections](https://github.com/sourcegraph/docs/blob/main/docs/admin/code_hosts/github.mdx?plain=1#L383) in each of the individual code host's doc pages

2024-09-25 16:48 UTC, MaedahBatool commented
@michaellzc thanks for the PR. I have changed the PR base to our docs working branch. There's some feedback from @loujar. Let me know when it's done. Appreciate your help here. 🙏

2024-09-25 16:50 UTC, MaedahBatool requested changes

2024-09-25 16:50 UTC, MaedahBatool commented on docs/admin/repo/auth.mdx
> +Some providers may require additional configuration, consult the code host specific documentation for more information.
Can we link to the docs here?

2024-09-25 16:50 UTC, MaedahBatool commented on docs/admin/repo/auth.mdx
> +This error indicates that the provided private key is not base64 encoded. Ensure that the private key is base64 encoded before providing it to Sourcegraph.
```suggestion
This error indicates that the provided private key is not `base64` encoded. Ensure that the private key is `base64` encoded before providing it to Sourcegraph.
```

2024-09-25 16:54 UTC, michaellzc commented
> I think we should also update the [_Configuration_ sections](https://github.com/sourcegraph/docs/blob/main/docs/admin/code_hosts/github.mdx?plain=1#L383) in each of the individual code host's doc pages

are you talking about the embedded jsonschema? I believe some automation is responsible to update them during release time.

2024-09-25 17:00 UTC, eseliger approved these changes

2024-09-25 17:00 UTC, eseliger commented on docs/admin/repo/auth.mdx
> +- **Option 1**: Configure the SSH credentials in code host configuration in the Web UI.
Should we mention that this is the much preferred option going forward?

2024-09-25 17:36 UTC, merged