Deep Cody docs
sourcegraph/docs pull request #841
Opened 2024-12-10 19:33 UTC by MaedahBatool

Docs for Deep Cody

2025-01-14 14:05 UTC, MaedahBatool commented on docs/cody/capabilities/agentic-chat.mdx
> +Update the `cody.agentic.context` setting to `allow` or `block` specific commands:
@graceshih-sg I need to double-check this section with you. Is it factually correct?

2025-01-14 20:43 UTC, abeatrix reviewed
left some comments inline for the changes

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Linear Issue Tool (via OpenCtx)**: Integrates with Linear issue tracking when the provider is configured
```suggestion
- **Code Search**: Performs code searches
- **Codebase File**: Retrieves the full content from a file in your codebase
- **Terminal**: Executes shell commands in your terminal
- **Chat Memory**: Allows the agent to create personal notes that can be used across chat sessions
- **Web Browser*: Searches the web for live context
- **OpenCtx**: Any OpenCtx providers could be used by the agent
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +<Callout type="info">Tool calling is not supported on the Web. It only works with VS Code and JetBrains editor extensions.</Callout>
```suggestion
<Callout type="info">Terminal access is not supported on the Web. It currently only works with VS Code and JetBrains editor extensions.</Callout>
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +## Terminal commands
```suggestion
## Terminal access
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +Agentic Chat can use the CLI Tool to execute shell commands and gather context from your terminal. Its ability to execute terminal commands enhances its context-gathering capabilities. However, it’s
```suggestion
You can configure Agentic Chat to execute shell commands and gather context from your terminal. Its ability to execute terminal commands enhances its context-gathering capabilities. However, it’s essential to understand that any information accessible via your terminal could potentially be shared with the LLM. It's recommended not to request information that you don't want to share. Here's what you should consider:
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Allow list configuration**: This feature is disabled if the allow list is empty. By default, the allow list is set to ['*'], which allows all commands. For enhanced security, use specific command
```suggestion
```

Since this is not tested, i'd suggest against mentioning it until it's ready.

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +Commands are generated by the agent/LLM based on your request. Avoid asking it to execute destructive commands if you do not want them to run.
```suggestion
Commands are generated by the agent/LLM based on your request. Avoid asking it to execute destructive commands.
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +You can configure shell command execution via the `cody.agentic.context` setting in your editor:
```suggestion
You can configure terminal access in the chat UI, under the agentic context settings.
```

<img width="664" alt="image" src="https://github.com/user-attachments/assets/0d53e82c-50d1-46ab-a9f5-919f8953995b" />

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +To disable the feature, navigate to your user settings and set `cody.agentic.context` to an empty value. When disabled, the chat agent cannot access the CLI.
@MaedahBatool  we have moved the settings out of the json file into the UI: 

<img width="664" alt="image" src="https://github.com/user-attachments/assets/dbf45962-802c-4649-8446-1d2fc68c356d" />

```suggestion
```

2025-01-14 20:43 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +As mentioned above, Agentic Chat's ability to execute terminal commands enhances its context-gathering capabilities. However, it’s essential to understand that any information accessible via your ter
We should mention how they can disable this feature by setting `agentic-chat-cli-tool-experimental`  to false

2025-01-14 22:45 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Allow list configuration**: This feature is disabled if the allow list is empty. By default, the allow list is set to ['*'], which allows all commands. For enhanced security, use specific command
+1 let's remove this line

2025-01-14 22:45 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +
```suggestion
* - **Requires user consent**: Agentic Chat will pause and ask for permission each time before executing any shell command.
```

2025-01-14 22:45 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +<Callout type="info">Agentic Chat is currently in the Experimental stage for Cody Pro and Enterprise and is supported only on VS Code, JetBrains editor extensions, and Web.</Callout>
```suggestion
<Callout type="info">Agentic Chat is currently in the Experimental stage for Cody Pro and Enterprise and is supported only on VS Code, JetBrains editor extensions, and Web. Usage may be limited at this stage.</Callout>
```

Need a better wording there but we should call out that we may enforce limits on usage (and subject to change).

2025-01-14 22:45 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +Agentic Chat can use the CLI Tool to execute shell commands and gather context from your terminal. Its ability to execute terminal commands enhances its context-gathering capabilities. However, it’s
```suggestion
Agentic Chat can use the CLI Tool to request execution of shell commands in order to gather context from your terminal. Its ability to execute terminal commands enhances its context-gathering capabilities. However, it’s essential to understand that any information accessible via your terminal could potentially be shared with the LLM. It's recommended not to request information that you don't want to share. Here's what you should consider:
```

(Mainly want to make it clear, we will always ask permission before executing a command)

2025-01-20 16:58 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +Update the `cody.agentic.context` setting to `allow` or `block` specific commands:
Let's leave out the allowlist/blocklist -- we decided to not expose it at launch.

2025-01-20 16:58 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +
Let's remove this block -- does that sound okay @abeatrix?

2025-01-20 22:58 UTC, aramaraju requested changes
Left some comments in, some major ones to be aware of:

- Update the name to be a common noun instead of a proper noun
- UX is still in flux as the Onebox team is looking to integrate it into the box, instead of outside
- UX for Accept/Reject terminal commands was added
- Be clear on the why you need Haiku and it's okay to reiterate the Enterprise requirements in multiple places

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +<p className="subtitle"> Learn about the Agentic Chat experience, an exclusive chat-based AI agent with enhanced capabilities.</p>
"agentic chat" is not a proper noun from a marketing POV, let's update this in the rest of the doc @MaedahBatool

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +This Agentic Chat experience aims to reduce the learning curve associated with traditional coding assistants by minimizing users' need to provide context manually. It achieves this through agentic co
It also helps retrieve context from other tools such as terminal, OpenCtx, etc dynamically as needed to better answer the query

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Agentic context review**: Reviews the gathered context to ensure it is comprehensive and relevant to your query
Let's use "reflection" - review is an overloaded word

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +Pro users can enable the Agentic Chat experience from the green **funnel** icon in Cody's chat panel. You can toggle the **Agentic Chat** feature on and off. Enterprise customers are required to opt-
Heads up - @beyang proposed a new UX for the agentic chat that is changing this experience, so we will have to update these instructions/images

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +Enterprise customers can get access by upgrading their supported client (VS Code, JetBrains, and Visual Studio) to the latest version of the plugin and enabling the following feature flags on their S
Currently they also need Haiku 3.5 available for their instance

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +Update the `cody.agentic.context` setting to `allow` or `block` specific commands:
+1 ^

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Improved response quality**: Helps you get better and more accurate responses than other LLMs, making the additional processing time for context gathering a non-issue
Did you mean "making up for" ? Little confused by the second half of the sentence

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +Cody Gateway customers are required to have Claude 3.5 Haiku enabled (this requires Sourcegraph v5.9 and new [model configuration](/cody/enterprise/model-configuration)). BYOK customers will use the
It's worth putting a disclaimer - "Currently, agentic chat uses Claude 3.5 Haiku for the reflection steps as it provides a good balance between quality and latency. The Enterprise instance must have access to Claude 3.5 Haiku to use agentic chat ..... "

2025-01-20 22:58 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +As mentioned above, Agentic Chat's ability to execute terminal commands enhances its context-gathering capabilities. However, it’s essential to understand that any information accessible via your ter
+1

2025-01-23 18:09 UTC, MaedahBatool commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Improved response quality**: Helps you get better and more accurate responses than other LLMs, making the additional processing time for context gathering a non-issue
Yes this

2025-01-23 18:23 UTC, MaedahBatool commented on docs/cody/capabilities/agentic-chat.mdx
> +You can configure shell command execution via the `cody.agentic.context` setting in your editor:
@abeatrix where will this option live with the new UI?

2025-01-27 17:05 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +- Users will also need to manually enable access to the terminal commands on the client's `settings.json` file i.e., set `"cody.agentic.context.experimentalShell": true`
```suggestion
```

Since all commands are now required manual approval before it runs, this setting has been removed

2025-01-27 17:05 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +Cody Gateway customers are required to have Claude 3.5 Haiku enabled (this requires Sourcegraph v5.9 and new [model configuration](/cody/enterprise/model-configuration)). BYOK customers will use the
```suggestion
All customers are required to have Claude 3.5 Sonnet and Claude 3.5 Haiku enabled on their Sourcegraph instance (this requires Sourcegraph v5.9 and new [model configuration](/cody/enterprise/model-configuration)).
```

2025-01-27 17:05 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +As mentioned above, agentic chat's ability to execute terminal commands enhances its context-gathering capabilities. However, it’s essential to understand that any information accessible via your ter
```suggestion
```

This seems to be duplicated of the Terminal access section above

2025-01-27 17:05 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +Currently, agentic chat uses Claude 3.5 Haiku for the reflection steps as it provides a good balance between quality and latency. Your enterprise instance must have access to Claude 3.5 Haiku to use
```suggestion
Currently, agentic chat uses Claude 3.5 Haiku for the reflection steps and Claude 3.5 Sonnet for the final response to provide a good balance between quality and latency. Your enterprise instance must have access to both Claude 3.5 Sonnet and Claude 3.5 Haiku to use agentic chat.
```

2025-01-27 17:34 UTC, aramaraju commented on src/data/navigation.ts
> +							{ title: "Agentic Chat", href: "/cody/capabilities/agentic-chat", },
```suggestion
							{ title: "Agentic chat", href: "/cody/capabilities/agentic-chat", },
```

2025-01-27 21:18 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +Currently, agentic chat uses Claude 3.5 Haiku for the reflection steps and Claude 3.5 Sonnet for the final response to provide a good balance between quality and latency. Your enterprise instance mus
It's a double-edged sword. We need to explicitly state the models for customers to make sure they have it enabled, but I concede that this makes it harder to change the models later.

How about a slight tweak @graceshih-sg :
For the experimental release, agentic chat is specifically limited to using Claude 3.5 Haiku for the reflection steps and Claude 3.5 Sonnet for the final response to provide a good balance between quality and latency. Therefore, your enterprise instance must have access to both Claude 3.5 Sonnet and Claude 3.5 Haiku to use agentic chat. These models may be changed during the experimental phase to optimize for quality and/or latency.

2025-01-27 21:19 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +- `agentic-chat-cli-tool-experimental` to allow [terminal access](#terminal-commands)
Yup - let's go ahead for Enterprises. Any specific objections @graceshih-sg ?

2025-01-27 22:38 UTC, graceshih-sg commented on docs/cody/capabilities/agentic-chat.mdx
> +- `agentic-chat-cli-tool-experimental` to allow [terminal access](#terminal-commands)
Mostly just the feature set between PLG and enterprises -- keeping it as close as possible is preferable. So offering additional flags just for enterprises, want to make sure we're okay supporting that. But I'm fine if this is experimental and we may change how all of this works later anyway.

2025-01-27 22:52 UTC, aramaraju commented on docs/cody/capabilities/agentic-chat.mdx
> +- `agentic-chat-cli-tool-experimental` to allow [terminal access](#terminal-commands)
Ah the feature flags are the same for both offerings, we are just turning them on for PLG vs asking customers to turn it on for Enterprise

2025-01-28 00:54 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +- **Chat Memory**: Allows the agent to create personal notes that can be used across chat sessions
```suggestion
```

Let's not include Chat Memory as tool for now as it is still in rough shape and we have just identified a bug with it.

2025-01-28 17:40 UTC, MaedahBatool commented on docs/cody/capabilities/agentic-chat.mdx
> +Currently, agentic chat uses Claude 3.5 Haiku for the reflection steps and Claude 3.5 Sonnet for the final response to provide a good balance between quality and latency. Your enterprise instance mus
I like this direction. I'll add this version.

2025-01-28 23:48 UTC, abeatrix approved these changes
left some comments in line. the rest looks good to me.

2025-01-28 23:48 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +<Callout type="info">Terminal access is not supported on the Web. It currently only works with VS Code and JetBrains editor extensions.</Callout>
```suggestion
<Callout type="info">Terminal access is not supported on the Web. It currently only works with VS Code, JetBrains, and Visual Studio editor extensions.</Callout>
```

2025-01-28 23:48 UTC, abeatrix commented on docs/cody/capabilities/agentic-chat.mdx
> +Memory allows the agentic chat to learn and remember your preferences, enabling a more personalized experience. You can ask it to **remember** specific details for future interactions.
```suggestion
```

2025-01-29 07:00 UTC, MaedahBatool commented
Thanks everyone for contributing. I am merging this PR to our release branch. Any follow-up changes will be tackled later after the release. Let's go! 🚀

2025-01-29 07:14 UTC, merged